### ISSUE TITLE
Pause a simulation and check if it has to continue from Python?

### ISSUE THREAD

**Issue by paugier** [exabl/snek5000#101]
> We can't support this since Nek5000 simply starts from `case0.f00001` everytime it restarts and overwrites the existing files. That's why I made this session mechanism in the first place.

_Originally posted by @ashwinvis in https://github.com/exabl/snek5000/issues/90#issuecomment-967561595_

We would need to be able to stop a simulation as soon as something had happen (in practice the growth of a linear instability). It is very easy to check from Python with the data saved in the .his file (history points). I guess we could add some code in the .usr file (subroutine `userchk`) to pause Nek5000 and act depending on a response of Python.

@ashwinvis Any thoughts on the feasibility of this plan? How should the 2 processes communicate? Just stdin in Fortran?

**Comment by paugier** [comment]
Note: this would be the first step towards a tighter interaction between Nek and Snek. With such mechanism, we would be able to do some tasks (for example on the fly output) in Python during the simulation. For output, we would need to transfer data from Nek to Snek, which is not necessary for the application described in the issue (check if the simulation has to continue).

**Comment by ashwinvis** [comment]
Very cool idea.

A simple way I can see this happening is to launch a simulation in the background `sim.make.exec("run")`, and have the Python loop inspecting the output in an event loop. If the output is on the filesystem, it is relatively easy to implement. We need to know the process ID somehow if we have to correctly issue a "kill" / "terminate" signal.

To integrate directly, there is this approach used by the AMUSE framework. For example see this article on how DALES (a Fortran LES code) exposes a Python interface using AMUSE / OMUSE.

https://www.sciencedirect.com/science/article/pii/S2352711020303216

**Comment by paugier** [comment]
We now have a nice example of how it could be done with "the simple way" : https://github.com/exabl/snek5000-cbox/pull/10

This depends on #112  (now ready to be merged).

This depends on an mpirun option only available with OpenMPI. To activate this option, we now need to use a particular config file with `MPIEXEC_FLAGS: "--oversubscribe --report-pid PID.txt"`.

It would be much better to be able to specify this environment variable in the script as explained in #109.

This method uses the signal `SIGTERM` to terminate the Nek processes. I didn't find a gentler way to tell Nek to stop the simulation. Unfortunately, with `SIGTERM`, Nek just suddenly stops and does not run its finalization process.

Remark:

This is indeed a first step on controlling a simulation from Python. I think there are 3 methods:

1. Communication through hard disk and signals as in https://github.com/exabl/snek5000-cbox/pull/10
2. Communication between Python and Nek processes via a dedicated library. Since Nek already uses MPI, it makes sense to use MPI also to send data. I think it would be doable but it requires some additional code in the .usr file.
3. Calling Nek Fortran API from Python (like with the AMUSE framework if I understand correctly). Much finer control but a lot of work to implement.

1. is simple and already a very nice step.
2. would allow Snek to process Nek data during the simulation without IO on disk.
3. is in my point of view a too ambitious project for Nek5000.

I think we can close this issue as soon as we find a good solution for #109. Maybe we can then open a new long-term issue on solution 2.

**Comment by paugier** [comment]
Closed by #113 and #112
