### ISSUE TITLE
More efficient sim.output.history_points.load

### ISSUE THREAD

**Issue by paugier** [exabl/snek5000#108]
It would be nice to save the result of `sim.output.history_points.load` and read only the new lines in the .his file.

This would dramatically improve the performance of `sim.output.history_points.load` (https://github.com/exabl/snek5000/blob/main/src/snek5000/output/history_points.py#L59).

**Comment by paugier** [comment]
Necessary for https://github.com/exabl/snek5000-cbox/pull/10

**Comment by ashwinvis** [comment]
Could be done using `os.lseek` or `np.loadtxt(..., skiprows=...)`

**Comment by paugier** [comment]
See https://github.com/exabl/snek5000/tree/faster-history-points-load

It seems to work. It needs to be better tested. @akhoubani You can now use this branch for you simulations with run_simul_check_from_python.py!
