### ISSUE TITLE
Set environment variables from `sim.make.exec`

### ISSUE THREAD

**Issue by paugier** [exabl/snek5000#109]
If I understand well, overriding environment variables requires modifying the Snakefile:

https://snek5000.readthedocs.io/en/latest/configuring.html#overriding-configuration-with-environment-variable

It would be nice to be able to override environment variables from `sim.make.exec`.

**Comment by paugier** [comment]
Related to exabl/snek5000-cbox#10

**Comment by paugier** [comment]
Hum, it does not seem easy. @ashwinvis do you see how it could be done ?

See https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#environment-variables

**Comment by ashwinvis** [comment]
That won't do it. From the docs that you linked above:

> However, note that this does not mean that Snakemake makes them available e.g. in the jobs shell command... you are required to pass them explicitly 

This is why I made environment variables globally configurable via the `config` dictionary. What you can do is do something like:

```py
configfile: get_configfile(host="dev")
```

Which would look for a different configfile `dev.yml` at the specific locations. Of course, this would not be so dynamic as you wish.

Alternatively, define your own `configfile_from_params` function which reads the `params_simul.xml` and returns a configuration file.

**Comment by ashwinvis** [comment]
More alternatives!

Write a `config_simul.yml` during `sim.output.post_init()` call and hardcode

```yaml
configfile: "config_simul.yml"
```

**Comment by paugier** [comment]
We need a way to send an environment variable without modifying the Snakefile. Because a user of snek5000 based solver cannot easily modify the Snakefile (except it there is something that I didn't understand correctly).
