### ISSUE TITLE
Potential use case: lateral convection in a parallelepiped box ?

### ISSUE THREAD

**Issue by paugier** [exabl/snek5000#11]
Hi @ashwinvis 

I'd like to ask you your opinion on a potential use case of snek5000 (with potentially a PhD student working on that).

I'd need to run simulations of a convective flow in a parallelepiped box forced by heat fluxes on 2 sides.

DNS of the 3d Navier-Stokes equations under the Boussinesq approximation with a no-slip boundary condition for the velocity.

The boundary condition for the buoyancy (or temperature) should be more complicated with, depending on the surface, fixed T or fixed gradient. It would even be nice to be able to impose a temperature profile on the sides.

It could also be necessary to add turbulence models.

It would also be nice to be able to model the effect of a static grid with a simple immersed boundary method.

What do you think about this use case for snek5000?

**Comment by ashwinvis** [comment]
Some things you should know what you can do easily

1. There is an official example of [Rayleigh Benard convection](https://github.com/Nek5000/NekExamples/tree/master/rayleigh) which could be a good starting point.
2. Complex, arbitary shaped meshes

**Comment by ashwinvis** [comment]
So as I mentioned, most of the development would be adding a bunch of subroutines to define initial conditions, forcing or setting other physical properties. This has to be done in the Fortran part (see [case files](https://nek5000.github.io/NekDoc/problem_setup/case_files.html)). `snek5000` can make it easier to set different parameters, compilation and launching various simulations etc.

So yes it is feasible. Let me know if you need more info.

**Comment by ashwinvis** [comment]
Some downsides of Nek5000 are more deep with the software architecture being used. Modern way of software development such as: interfacing with other languages, use of debugger, modifying the Nek5000 core, writing unit tests would be a tough task. Perhaps not impossible, but I do not see clear paths for doing this yet.

These were all sacrificed for performance, I think.

**Comment by paugier** [comment]
Thanks for your detailed and honest answers !

I think it is now reasonable in terms of performance to have the main time stepping loop in Python (to do some processing during the simulation in Python) and call some Fortran methods for the time advancement. When doing that, it is mandatory to be able to get the arrays corresponding to the state without copy.

If you think that it could be possible I would be motivated to invest some time on this.

**Comment by ashwinvis** [comment]
I think it is possible, since the main event loop in Nek5000 is rather simple: https://github.com/Nek5000/Nek5000/blob/v19.0/core/drive.f. Also at one point I managed to compile a dynamic library instead of an executable from all the sources. I did not manage to load it with cffi with its ABI mode, so the next thing to see is if it is possible to make it work with the cffi API mode.

Yet another reason why I think this is feasible is because of nekRS, the sister project of Nek5000 to use GPUs. If you look here, they are building a `.so` file out of it.

https://github.com/Nek5000/nekRS/tree/next/src/nekInterface

**Comment by ashwinvis** [comment]
The state of the arrays is a global common block. https://github.com/Nek5000/Nek5000/blob/v19.0/core/SOLN#L32. And if [`f2py` can deal with common blocks](https://numpy.org/devdocs/f2py/python-usage.html#common-blocks), it should not be a problem.

**Comment by paugier** [comment]
> The state of the arrays is a global common block.

Good but on the other hand, it might be impossible to initialize more than 1 simulation in the same process.

**Comment by ashwinvis** [comment]
Other than the built-in feature for overlapping grids called [NekNek](https://nek5000.github.io/NekDoc/search.html?q=neknek&check_keywords=yes&area=default), I wonder why one would need that.

**Comment by paugier** [comment]
There are applications, for example 2 coupled simulations (with different time increments, equations and grids) or even just:

```python
from fluidsim import load_state_phys_file as load
sim = load(path0)
# postproc
sim = load(path1)
# postproc
```

**Comment by ashwinvis** [comment]
Coupled simulations are possible, with NekNek - afaik, it runs two instances of Nek5000 communicating with each other - but I have no experience in this. For postprocessing, I load state files using the package `pymech` which is pure python. I extended it with xarray recently, and can be used as follows:

https://nbviewer.jupyter.org/github/jcanton/pymech/blob/master/docs/usage.ipynb

**Comment by paugier** [comment]
Ok good to know.

`pymech` seems really nice ! But I guess you can't use NEK5000 operators.

**Comment by ashwinvis** [comment]
Yeah, that's a problem. That would need some interfacing.

**Comment by ashwinvis** [comment]
I made a simple test case to test our understanding of Fortran 77 and CFFI: 

https://github.com/exabl/sandbox/tree/master/interface/test_case

**Comment by paugier** [comment]
We are trying to write a new solver in https://github.com/exabl/snek5000-cbox/ ! WIP...

Few issues should come :slightly_smiling_face:

**Comment by paugier** [comment]
https://github.com/exabl/snek5000-cbox is now working quite well. Still work to do but it's already very nice!
