### ISSUE TITLE
Take into account ~/.config/snek5000/configfile.yml

### ISSUE THREAD

**Issue by paugier** [exabl/snek5000#110]
See https://snek5000.readthedocs.io/en/latest/configuring.html

I think now only ~/.config/snek5000/<hostname>.yml is taken into account.

**Comment by ashwinvis** [comment]
I don't understand. Is this a documentation issue? Snek5000 looks for the 3 places in total.

https://github.com/exabl/snek5000/blob/3788fe9ed06ad746cb30a76d2ae92b853349521b/src/snek5000/output/base.py#L209-L227

**Comment by paugier** [comment]
The problem is with the `f"{host}.yml"`. On a cluster, we would need one config file per node, since {host} is different for each node.

**Comment by paugier** [comment]
See https://github.com/exabl/snek5000/commit/2c7ac9e5a37720c215c7be28c49071698c64658e (I'm going to create the PR when #107 will be merged).

**Comment by ashwinvis** [comment]
@paugier This is good to go.
