### ISSUE TITLE
Simulation fails in "run" mode.

### ISSUE THREAD

**Issue by akhoubani** [exabl/snek5000#122]
I noticed that simulation fails in the "run" mode. I use [https://github.com/akhoubani/snek5000-cbox/tree/fix/run-mode](url) with main branch of snek and the nek directory of snek. I leave here also the OAR logs. 

[OAR.stderr.txt](https://github.com/exabl/snek5000/files/7736972/OAR.stderr.txt)
[OAR.stdout.txt](https://github.com/exabl/snek5000/files/7736973/OAR.stdout.txt)

When I use "run_fg" it works.

**Comment by ashwinvis** [comment]
The `run` rule executes in the background and it is understandable if the job scheduler would kill the job if there is no running process in the foreground. Is that is what is happening? If you want to use `run`, keep the `while check_running():` loop.

**Comment by akhoubani** [comment]
Thanks for the comment. I didn't know. It works as you say.
