### ISSUE TITLE
Running the Periodic Hill case 

### ISSUE THREAD

**Issue by akhoubani** [exabl/snek5000#17]
Hello @ashwinvis 

I have tried to run the Periodic Hill case. I followed the guidance on [this](https://snek5000.readthedocs.io/en/latest/ipynb/executed/tuto_simul.html) page. The `!ls {sim.path_run}` command, gives the following:

`build.log  info_solver.xml  makefile nek5000  params_simul.xml  phill.box  phill.log  phill.par  phill.usr SIZE templates etc	logs		    makefile_usr.inc  obj params.xml  phill.f    phill.ma2  phill.re2  SESSION.NAMESnakefile  toolbox
`

Which means it does not give me the result of simulation `(rs6phill0.f00001 ...)`. I tried `sim.make.exec('test') ...`, it gives 
` Changing to shadow directory: ../Sim_data/phill_run_2021-01-25_12-12-27`
`Building DAG of jobs...`
`MissingRuleException:`
`No rule to produce e (if you use input functions make sure that they don't raise unexpected exceptions).`
`Out[9]: False`

I do not know if it is related. I wonder if you could help me with this issue.

**Comment by ashwinvis** [comment]
Hi @akhoubani, the `sim.make.exec(rules=...)` method would only respond to the rules specified in the `Snakefile`. You can see that `test` is not a rule.  If you executed `sim.make.list()` you would see all the available rules. Hope that helps.

**Comment by ashwinvis** [comment]
Also @akhoubani, it is important to have Nek5000 in your machine and the following environment variables set before executing `snek5000`
```sh
export NEK_SOURCE_ROOT="/path/to/Nek5000"
export PATH="$PATH:$NEK_SOURCE_ROOT/bin"
```

**Comment by ashwinvis** [comment]
Since the mesh was generated and `nek5000` executable was produced, I see you have the necessary dependencies. Maybe attach `phill.log` here so that we can look at any runtime error messages. You could also try `sim.make.exec(['srun'])' instead.

**Comment by akhoubani** [comment]
Thank you very much @ashwinvis for your fast reply. Included you will find the `phill.log` of `sim.make.exec(['srun'])`. 
[phill.log](https://github.com/exabl/snek5000/files/5866576/phill.log)

Also the `.log` that is saved in `nek5000` directory. 
[2021-01-25T133739.773720.snakemake.log](https://github.com/exabl/snek5000/files/5866592/2021-01-25T133739.773720.snakemake.log)

Thank you for your time.

**Comment by ashwinvis** [comment]
Here is the error:

```log
  Error: Nek has has been compiled for
         number of elements/proc  (lelt):         128
         total number of elements (lelg):        1024

  This run requires:
     lelt >=          960  for np =            1
     lelg >=          960

  
an error occured: dying ...
```

The number of processors are detected [using a standard Python here](https://github.com/exabl/snek5000-phill/blob/master/src/phill/Snakefile#L84). Not sure why that did not work. Can you open a Python console and try the following:

```py
In [1]: import os

In [2]: os.cpu_count()
Out[2]: 4

In [3]: import multiprocessing

In [4]: multiprocessing.cpu_count()
Out[4]: 4

In [5]: import psutil

In [6]: psutil.cpu_count()
Out[6]: 4
```

**Comment by akhoubani** [comment]
Here it is:

<pre><font color="#008700">In [</font><font color="#586E75"><b>1</b></font><font color="#008700">]: </font><font color="#008700"><b>import</b></font> <font color="#0087D7"><b>os</b></font>

<font color="#008700">In [</font><font color="#586E75"><b>2</b></font><font color="#008700">]: </font>os.cpu_count()
<font color="#870000">Out[</font><font color="#CB4B16"><b>2</b></font><font color="#870000">]: </font>8

<font color="#008700">In [</font><font color="#586E75"><b>3</b></font><font color="#008700">]: </font><font color="#008700"><b>import</b></font> <font color="#0087D7"><b>multiprocessing</b></font>

<font color="#008700">In [</font><font color="#586E75"><b>4</b></font><font color="#008700">]: </font>multiprocessing.cpu_count()
<font color="#870000">Out[</font><font color="#CB4B16"><b>4</b></font><font color="#870000">]: </font>8

<font color="#008700">In [</font><font color="#586E75"><b>5</b></font><font color="#008700">]: </font><font color="#008700"><b>import</b></font> <font color="#0087D7"><b>psutil</b></font>

<font color="#008700">In [</font><font color="#586E75"><b>6</b></font><font color="#008700">]: </font>psutil.cpu_count()
<font color="#870000">Out[</font><font color="#CB4B16"><b>6</b></font><font color="#870000">]: </font>8
</pre>

**Comment by akhoubani** [comment]
Dear @ashwinvis, 

I upgraded to Ubuntu 20.04 and now it works. Thank you for your time.

**Comment by ashwinvis** [comment]
Thank you for trying `snek5000` out, and do not hesistate if you have any questions / requests.
