### ISSUE TITLE
Setting up a simulation

### ISSUE THREAD

**Issue by akhoubani** [exabl/snek5000#18]
Dear @ashwinvis, 

In order to set up a simulation, assuming that we modified the `.box`, `.usr`, `.par` files, what would be the next steps?

I have tried to do so, while the procedure was not clear for me. I wonder if you could give me some advice.

Thank you for your time and future reply, regards.

**Comment by ashwinvis** [comment]
When you say "modified", do you mean:
1. modify it via snek5000 `params`? 
1. modify the default templates to add more functionality?

If it is the **first case**, once you modify `params` to suit your case `sim = Simul(params)` would write all the source code to your disk. Then `sim.make.exec()` can then do many things including compiling, generating mesh, running the simulation etc.

If it is the **second case**, you need to put the modified templates under a directory like `phill/templates` and load them as shown here:

https://github.com/exabl/snek5000-phill/blob/8753fe7847320412427aa6ad75af8361d52523c5/src/phill/templates/__init__.py#L15-L25

Import the templates into the output class like done here:

https://github.com/exabl/snek5000-phill/blob/8753fe7847320412427aa6ad75af8361d52523c5/src/phill/output.py#L3

**Comment by akhoubani** [comment]
Thank you for your time and explanation.

This is the second case and I aim to simulate the circulation in a differentially heated cavity. In order to do so, I managed to modify the `.box` and etc. I'll follow the procedure you mentioned.

**Comment by ashwinvis** [comment]
Let me know when you get stuck, find some information is lacking. It can be a useful tutorial on how to implement a solver using this framework.

**Comment by ashwinvis** [comment]
@akhoubani We have simplified the workflow a lot and added a tutorial here. https://snek5000.readthedocs.io/en/latest/packaging.html
