### ISSUE TITLE
API similar to `fluidsim.load_sim_for_plot` and `sim.output.phys_fields.get_var`?

### ISSUE THREAD

**Issue by paugier** [exabl/snek5000#21]
I think it would be useful to recreate a Simul object from a directory. It would be a nice way to read the parameters and the results from Python.

It would be really nice to be able to load a particular field with the `sim` object (returned as a Numpy array). And even to read a particular cross-section.

**Comment by ashwinvis** [comment]
Oops, I missed the issue notification somehow! I agree that plotting results has to be fixed soon... for my own sake too. A very barebones simulation loader exists here:

https://github.com/exabl/snek5000/blob/35bc433e917f83bc6aeb290cb6fd2f9161e724e2/src/snek5000/__init__.py#L72-L110

To plot the results, I need to make use of pymech here.

**Comment by ashwinvis** [comment]
I have took inspiration from the architecture of `InitFields` and `SpecificInitFields` classes in fluidsim, to design the `PhysFields` and `Reader` classes respectively.

**Comment by paugier** [comment]
Can we close this one now that #7 has been merged ?

**Comment by ashwinvis** [comment]
I will add a short update to the `load` function to invoke `init_reader` via a parameter.
