### ISSUE TITLE
Names of packages using snek5000

### ISSUE THREAD

**Issue by paugier** [exabl/snek5000#25]
I'd like to create a new package for another case. I'd like to address the problem of naming convention in this issue.

I'd like to call the solver `heated_box` and the package `snek5000_heated_box`. I can't do that because of https://github.com/exabl/snek5000/blob/master/src/snek5000/output/base.py#L170:

```python
contents_pkg = resources.contents(name_solver)
```

Similarly I think it would be clearer for the main example to be called `snek5000_phill`. In the main tutorial (https://snek5000.readthedocs.io/en/latest/ipynb/executed/tuto_simul.html), we soon see `import phill` but the reader doesn't know what is `phill` and that `phill` contains a `snek5000` solver written using `snek5000`.

See the error I get when I try to `pytest`:

```
tests/conftest.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../snek5000/src/snek5000/solvers/base.py:208: in __init__
    self.output.post_init()
src/snek5000_heated_box/output.py:35: in post_init
    super().post_init()
../snek5000/src/snek5000/output/base.py:371: in post_init
    self.copy(self.path_run)
../snek5000/src/snek5000/output/base.py:235: in copy
    abs_paths = self.get_paths()
../snek5000/src/snek5000/output/base.py:215: in get_paths
    paths += [self.root / resource for resource in self._get_resources()]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <snek5000_heated_box.output.OutputHeatedBox object at 0x7fc89abadd30>, name_solver = 'heated_box'

    def _get_resources(self, name_solver=None):
        """Get a generator of resources (files) in a package, excluding
        directories (subpackages).
    
        :returns: generator
    
        """
        excludes = self.excludes
        if not name_solver:
            name_solver = self.name_solver
        try:
            contents_pkg = resources.contents(name_solver)
        except TypeError:
            return ()
        except ImportError:
>           raise FileNotFoundError(
                f"Cannot resolve subpackage name_solver={name_solver} at root={self.root}"
            )
E           FileNotFoundError: Cannot resolve subpackage name_solver=heated_box at root=/home/pierre/Dev/snek5000-heatedbox/src/snek5000_heated_box

../snek5000/src/snek5000/output/base.py:176: FileNotFoundError

```

**Comment by ashwinvis** [comment]
I agree... and that particular file requires some refactoring. This way of importing was done before I introduce the entrypoints system:

```ini
[options.entry_points]
snek5000.solvers =
    phill = phill.solver
```

So if I understood correctly, there are two things to do:

- [ ] Clarify in docs how to create a new user project (also related to #26)
- [ ] Use the entrypoints to resolve solver paths

**Comment by ashwinvis** [comment]
> I'd like to call the solver heated_box and the package snek5000_heated_box. I can't do that because of

But in your case you *should* rename the path as `src/heated_box` instead of `src/snek5000_heated_box`?

**Comment by paugier** [comment]
> But in your case you should rename the path as src/heated_box instead of src/snek5000_heated_box?

If I do that, I would need to import as `import heated_box` and not `import snek5000_heated_box`. I would really prefer to import as `import snek5000_heated_box`.

**Comment by ashwinvis** [comment]
OK, I understand
