### ISSUE TITLE
Automating time order in the SIZE file

### ISSUE THREAD

**Issue by akhoubani** [exabl/snek5000#45]
When I change the time integration order for instance as:

`params.nek.general.time_stepper = 'BDF3'`,

it doesn't change the `params.oper.max.order_time` to 3 and it should be done manually like:

`params.oper.max.order_time = 3`.

This `order_time` is equal to 2 by default. It would be nice to automate it as a conditional statement. There are three possible time integration order as:

`'BDF1', 'BDF2', and 'BDF3'`.

**Comment by ashwinvis** [comment]
I will change the parameter into a property of the `Operators` class.
