### ISSUE TITLE
Snek5000.load() does not load parameters

### ISSUE THREAD

**Issue by akhoubani** [exabl/snek5000#52]
When I want to load a simulation (in particular I need parameters), it seems to me that the `Snek5000.load()` or `Snek5000.load_simul()` does not work properly. 
<pre><font color="#DC322F">WARNING </font> Expected a configuration file describing compilers and flags: <font color="#D33682">/home/arman/Dev/snek5000-cbox/src/snek5000_cbox/etc/</font><font color="#6C71C4">khouban.yml</font>                                      <font color="#576364">base.py</font><font color="#576364">:130</font>
<font color="#1C6B65">                    </font><font color="#268BD2">INFO    </font> Using default configuration instead: <font color="#D33682">/home/arman/Dev/snek5000/src/snek5000/assets/</font><font color="#6C71C4">default_configfile.yml</font>                                                           <font color="#576364">base.py</font><font color="#576364">:135</font>
<font color="#1C6B65">                    </font><font color="#268BD2">INFO    </font> ******************************************                                                                                                                         <font color="#576364">base.py</font><font color="#576364">:458</font>
<font color="#1C6B65">                    </font><font color="#268BD2">INFO    </font> solver: <font color="#E51515"><b>&lt;</b></font><font color="#6C71C4"><b>class</b></font> <font color="#859900">&apos;snek5000_cbox.output.OutputCbox&apos;</font><font color="#E51515"><b>&gt;</b></font>                                                                                                                  <font color="#576364">base.py</font><font color="#576364">:459</font>
<font color="#1C6B65">                    </font><font color="#268BD2">INFO    </font> path_run: <font color="#D33682">/home/arman/Sim_data/examples_cbox/</font><font color="#6C71C4">cbox_run_12x12x8_V1.x1.x1._2021-09-20_14-51-20</font>                                                                        <font color="#576364">base.py</font><font color="#576364">:460</font>
<font color="#1C6B65">                    </font><font color="#268BD2">INFO    </font> ******************************************                                                                                                                         <font color="#576364">base.py</font><font color="#576364">:461</font>
sim:                &lt;class &apos;snek5000_cbox.solver.SimulCbox&apos;&gt;
<font color="#1C6B65">                    </font><font color="#268BD2">INFO    </font> Searching for a log file<font color="#B58900">...</font>                                                                                                                                 <font color="#576364">print_stdout.py</font><font color="#576364">:29</font>
sim.output:         &lt;class &apos;snek5000_cbox.output.OutputCbox&apos;&gt;

<font color="#008700">In [</font><font color="#586E75"><b>5</b></font><font color="#008700">]: </font>sim
<font color="#DC322F">---------------------------------------------------------------------------</font>
<font color="#DC322F">NameError</font>                                 Traceback (most recent call last)
<font color="#859900">&lt;ipython-input-5-9600928f0943&gt;</font> in <font color="#2AA198">&lt;module&gt;</font>
<font color="#859900">----&gt; 1</font><font color="#DC322F"> </font>sim

<font color="#DC322F">NameError</font>: name &apos;sim&apos; is not defined

<font color="#008700">In [</font><font color="#586E75"><b>6</b></font><font color="#008700">]: </font>%who
snek5000	 
</pre>

**Comment by paugier** [comment]
How do you use the function ? I guess this should work:

```python
from snek5000 import load
sim = load()
```

**Comment by akhoubani** [comment]
Yes, it works.
