### ISSUE TITLE
Nek5000 reader

### ISSUE THREAD

**Issue by ashwinvis** [exabl/snek5000#6]
### Backend
- Paraview reader
- pymech

### References
- [entrypoints](https://github.com/takluyver/entrypoints/blob/master/entrypoints.py)
- https://intake.readthedocs.io/en/latest/plugin-directory.html#plugin-directory
- https://intake.readthedocs.io/en/latest/use_cases.html?highlight=xarray#distribute-data-in-a-custom-format
 
### Frontend
- intake-xarray (see [image backend](https://github.com/intake/intake-xarray/blob/master/intake_xarray/image.py))
- xarray 
- paraview python_view (section 4.12 in Paraview Guide 5.6)

**Comment by paugier** [comment]
Can we close this one now that #7 has been merged ?
