### ISSUE TITLE
Output class for stat of the KTH NEK5000 Framework

### ISSUE THREAD

**Issue by paugier** [exabl/snek5000#60]
After we will have #55, it would be also nice to have a class to interact with the stat toolbox from the KTH NEK5000 Framework

See https://kth-nek5000.github.io/KTH_Framework/group__stat.html

Maybe something like `params.output.stat` and `sim.output.stat` ...

**Comment by ashwinvis** [comment]
I will work on this now

**Comment by ashwinvis** [comment]
Done in #7, we have `pymech_stats`.
