### ISSUE TITLE
Include schedulers in cluster utilities

### ISSUE THREAD

**Issue by akhoubani** [exabl/snek5000#61]
It would be nice to improve a bit the cluster utilities to at least have OAR scheduler.

**Comment by ashwinvis** [comment]
The only cluster utility we have at the moment is `nproc_available`. I tried to read up the OAR docs, but I couldn't find an equivalent for `SLURM_NPROCS`. Can you start an interactive job of 1 or 2 nodes and check by running `/usr/bin/env`? Once we find that out, you can add it here:

https://github.com/exabl/snek5000/blob/a0c9a056fa52b5e0b5fe3ff89ecb4b7e931bc850/src/snek5000/clusters.py#L12

**Comment by akhoubani** [comment]
I don't know why it is searching for `.rea` file while we have `.re2`.

**Comment by paugier** [comment]
Let's close this issue!
