### ISSUE TITLE
Better mechanism for user params

### ISSUE THREAD

**Issue by paugier** [exabl/snek5000#73]
We'd like to use more user parameters in snek5000-cbox. For now, we need to write in the launching scripts:

```python
params.nek.general.user_params = {2: args.Prandtl, 3: args.Rayleigh}
```

This is fine for 2 parameters, but this is going to be ugly and error prone if we use much more user parameters.

Is there a mechanism to update `params.nek.general.user_params` depending on other parameters (for example something like `params.output.history_points.write_interval`) at the very beginning of the initialization of a simulation ?

**Comment by ashwinvis** [comment]
If you are writing a separate file, please try if [Fortran namelists](https://gcc.gnu.org/onlinedocs/gfortran/Extensions-to-namelist.html) work. If so there is a good Python package (https://pypi.org/project/f90nml/)

**Comment by ashwinvis** [comment]
Ah... sorry I read your question in a hurry. So you want to program in such a way that `params.nek.general.user_params` would depend on other parameters? The only mechanism we have is to inherit the `Simul.__init__` method and put your logic there.

**Comment by paugier** [comment]
I think we should add in https://github.com/exabl/snek5000/blob/master/src/snek5000/params.py a mechanism to record user parameters during functions like `create_default_params` or `_complete_params_with_default`.

Like that, some solvers could completely stop explicitly using `params.nek.general.user_params`.

The information about the recorded user parameters could be stored in an internal parameter of `params.nek.general` (for example in a dictionary `_recorded_user_params`).

In `create_default_params`, we could replace

```python
params.nek.general.user_params = {2: 0.71, 3: 1.8e8}
```

by something like

```python
params._set_attribs({"prandtl": 0.71, "rayleigh": 1.8e8})
params._record_nek_user_params({"prandtl": 2, "rayleigh": 3})
```

In `_complete_params_with_default` of the `HistoryPoints` class, we could also write

```python
params.output.history_points._set_attribs({"write_interval": 100})
params.output.history_points._record_nek_user_params({"write_interval": 4})
```

This would set the dictionary `params.nek.general._recorded_user_params` to `{2: "...prandtl", 3: "...rayleigh", 4: "...output.history_points.write_interval"}`, which would be used to produce the .par file.

This would be a better API to write the solvers and to use the solver (in the script).

This dictionary `params.nek.general._recorded_user_params` needs to be somehow written in the .par file (maybe in a comment?) to be able to correctly recreate the `params` objects from the .par file.

I think I could work on a PR on this new feature but please @ashwinvis tell me what you think about the idea.

**Comment by ashwinvis** [comment]
I like the general idea of **replacing parameters** and also **comments** in .par file.

How about this instead: **`lambda params: ...` as a legal value for Parameters**. This would enable a lot more dynamism and we can. In this context, we would need in `_complete_params_with_default`:
```py
params._set_attribs({"prandtl": 0.71, "rayleigh": 1.8e8})
```

and in `_complete_params_with_default` of the HistoryPoints class
```py
params.output.history_points._set_attribs({"write_interval": 100})
```

and in `create_default_params`
 
```py
params.nek.user_params = lambda params: {
    2: params.prandtl,
    3: params.rayleigh,
    4: params.output.history_points.write_interval,
}
```

These lambdas would then be replaced in place, with the return value during `Simul.__init__` -  like a preprocessor
. The **argument would always be the top level  `params` object.** 

An **advantage** is instead of just dictionaries and user_params more parameters can be dynamic. We can also use `min` and `max` in some cases. The only issue I could think of is how to ensure the lambdas would not be executed as pure functions.

**Comment by ashwinvis** [comment]
Then there is this question, should we make named callables made legal, and not just lambdas?

```py

def set_user_params(params):
    return {
      2: params.prandtl,
      3: params.rayleigh,
      4: params.output.history_points.write_interval,
    }

params.nek.user_params = set_user_params
```

Let me know what you think @paugier

**Comment by ashwinvis** [comment]
[Here is a discussion on lambdas as strings](https://stackoverflow.com/a/11112830). Either `eval` or some modified `literal_eval` would need to be upstreamed in `fluiddyn.util.paramcontainer` to achieve this.

**Comment by paugier** [comment]
Thanks for the feedback. We now have 2 different subjects:

1. better mechanism for Nek user parameters
2. dynamism in `params`, with `lambda` or something similar.

I tend to think that we should consider theses 2 subjects separately. We don't need real dynamism for Nek user parameters.

1. I tend to think we should remove `params.nek.general.user_params`. I don't see how this variable can really be useful in a launching script. This should be an internal parameter.

2. The approach "dynamic parameter object" is attractive (and also quite scary). I see some cases for which it would allow us to have better default parameters, for example

```python
params.oper.elem.order_out = "FROM_params: params.oper.elem.order"
params.oper.max.hist = "FROM_params: len(params.output.history_points.coords) + 1"
```
Note that I don't use `lambda params: ...` but rather `"FROM_params: ..."` because `lambda` is not well known (and also we would only support one parameter (`params`)).

I guess there are other examples where it can be useful.

I think we will need an `eval` in fluiddyn to support this (or maybe a custom `literal_eval` but it's going to be more complicated).

Note that this works: `eval("len(params.output.history_points.coords) + 1", {"params": params})`

### My conclusion

I think 1. should be done before 2. I'm not a big fan of 
```python
params.nek.user_params = lambda params: {...}
```
I don't see how and why users would use that in scripts, so I think it should be hidden.

Therefore, I'm going to work on a solution for 1. particular for Nek user parameters and not using `lambda`. Let see what it gives!

**Comment by ashwinvis** [comment]
Agreed with all your conclusions! Go ahead.
