### ISSUE TITLE
Doc on installing the paraview module 

### ISSUE THREAD

**Issue by paugier** [exabl/snek5000#87]
Yes, we can use in a "headless" mode without starting the GUI. Not always, but there are some ways where it would work from the standard Python / IPython console:

- The most generic way is to `conda install -c conda-forge paraview`
- In ArchLinux, the [paraview package is built with system python](https://github.com/archlinux/svntogit-community/blob/packages/paraview/trunk/PKGBUILD): `sudo pacman -S paraview; python -c 'import paraview'` works
- The Paraview way of using `pvpython` tool is a bit complicated. And the most common hack is to append the virtual environment site-packages path to `sys.path` or `$PYTHONPATH`. This would be the last resort.

_Originally posted by @ashwinvis in https://github.com/exabl/snek5000/pull/7#discussion_r589602818_

**Comment by paugier** [comment]
@akhoubani I think it is a good issue for you :slightly_smiling_face:  Could you please work on it?

Like that, you will learn how to modify the documentation.

You can start once #91 will be merged.

Note: with hg, I think you have nothing to do about the change master -> main. Just pull and update to main before starting this work. If you like, you can delete the old master bookmark like this `hg book -d master`.

**Comment by akhoubani** [comment]
> @akhoubani I think it is a good issue for you slightly_smiling_face Could you please work on it?
> 
Yes, I'll work on it.

> Like that, you will learn how to modify the documentation.
> 
> You can start once #91 will be merged.
> 
> Note: with hg, I think you have nothing to do about the change master -> main. Just pull and update to main before starting this work. If you like, you can delete the old master bookmark like this `hg book -d master`.

Thanks.

**Comment by paugier** [comment]
#91 has been merged so it is now time to work on this one!

**Comment by paugier** [comment]
@akhoubani do you need some help for this one ?

**Comment by paugier** [comment]
@akhoubani Please put the high priority label for this task. This is also a way to thanks @ashwinvis for its great help on what we are doing. If you need help, just tell me.

**Comment by akhoubani** [comment]
To be honest, it is not clear for me where should I add this explanation <https://github.com/exabl/snek5000/issues/87#issue-1044475626>. If I add it [here](https://snek5000.readthedocs.io/en/latest/install.html) is not convenient in my view. [Here](https://snek5000.readthedocs.io/en/latest/ipynb/executed/tuto_load_print_stdout.html) talks about post-processing but it is about something else. At [this page](https://snek5000.readthedocs.io/en/latest/_generated/snek5000.output.html#module-snek5000.output) which is under user guide menu, it is some how convenient, but I dislike to mix things. What I propose is that to allocate a section [here](https://snek5000.readthedocs.io/en/latest/install.html) for installing modules.

**Comment by ashwinvis** [comment]
You can either 
- create a section in `install.rst` or 
- create a standalone document say `install_opt.rst` and link it in `install.rst` using [a toctree directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html?highlight=toctree#directive-toctree)

I prefer the latter.

**Comment by akhoubani** [comment]
> You can either
> 
>     * create a section in `install.rst` or
> 
>     * create a standalone document say `install_opt.rst` and link it in `install.rst` using [a toctree directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html?highlight=toctree#directive-toctree)
> 
> 
> I prefer the latter.

I'll follow the later. Thanks.

**Comment by ashwinvis** [comment]
Some more tips:
- Run `make autobuild` under `./docs` to automatically render the result and preview it in the browser
- You can write in both Markdown or reStructuredText. That is up to you. Some useful docs:
  - rST: https://docutils.sourceforge.io/docs/ref/rst/directives.html, https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html
  - Markdown: https://myst-parser.readthedocs.io/en/latest/syntax/reference.html
