### ISSUE TITLE
Rename the default branch to main

### ISSUE THREAD

**Issue by paugier** [exabl/snek5000#88]
This is now the default for new projects on Github. Thus, we use `main` for snek5000-cbox. It would be nice to have the same name for the default branch for all snek repositories.

I don't know how it should be done, but I guess it's easy since so many projects on Github did it already.

**Comment by ashwinvis** [comment]
I can do that... GitHub has an easy way to set it in the web interface:

https://github.com/exabl/snek5000/settings/branches

I guess you are using hg-git and hope it would handle the change. Comment below if there is some difficulty switching the branch from `master` locally. If you are using git, these options are useful

```
git switch --create main
git push --set-upstream origin/main
```

cc: @akhoubani

**Comment by ashwinvis** [comment]
The default branch is now main. Github gave some other instructions (of course!).Copying it here.

>  The default branch has been renamed! master is now named main. If you have a local clone, you can update it by running the following commands. 
```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
