### ISSUE TITLE
Use the name short_name.usr.f for the user file in the packages

### ISSUE THREAD

**Issue by paugier** [exabl/snek5000#89]
It would be convenient to be able to use names like cbox.usr.f (for the .usr files) in the packages so that all editors easily understand that it is a f77 file.

**Comment by ashwinvis** [comment]
So in short snek5000 would copy `cbox.usr.f` to `cbox.usr` and then `makenek` would generate `cbox.f` and compile. It is possible, but we should delete the `cbox.usr` upon compilation then.

**Comment by ashwinvis** [comment]
It should be relatively easy. Have a look at this 

https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#protected-and-temporary-files

**Comment by paugier** [comment]
Silly question: where is the code responsible for copying `cbox.usr` in the simulation directory?

**Comment by ashwinvis** [comment]
Not just `.usr` but all source code: https://snek5000.readthedocs.io/en/latest/_generated/snek5000.output.base.html?#snek5000.output.base.Output.copy

Only SIZE, .box, .par and makefile_usr.inc are generated from the templates.
