### ISSUE TITLE
Load and restart issues

### ISSUE THREAD

**Issue by ashwinvis** [exabl/snek5000#90]
1. How to launch a simulation after just sim.make.exec(['compile'])? `load_simul` / `load_for_restart`. Should we error if SESSION.NAME is missing in `get_status`?
2. Failed simulation, say segfault / NaN. Snakemake encounters an error, would remove all the "output" files (as defined in the rule, not all simulation output) after a failed `run` / `run_fg`. There is the keyword argument `sim.make.exec(... keep_incomplete=True)` which keeps incomplete output files of failed jobs. But should it be default or not? 
3. `rs6...` restart files are created in `path_run` and not `path_session`.

**Comment by paugier** [comment]
> There is the keyword argument sim.make.exec(... keep_incomplete=True) which keeps incomplete output files of failed jobs. But should it be default or not?

+1 for `keep_incomplete=True` as default!

**Comment by paugier** [comment]
It is possible to restart to continue an existing session? We'd like to use something like that for idempotent jobs.

**Comment by ashwinvis** [comment]
We can't support this since Nek5000 simply starts from `case0.f00001` everytime it restarts and overwrites the existing files. That's why I made this session mechanism in the first place.

**Comment by akhoubani** [comment]
I encountered some problems in restarting the simulation for linear study which I'll try to summarize.

I use these lines for restarting using `cbox` in the simulation directory:

```python
from pathlib import Path

from snek5000.util import restart
from snek5000_cbox.solver import Simul


# path = Path.cwd()  # or the simulation path
params, Simul = restart.load_for_restart(use_start_from="cbox0.f00100")  # load params

# do the modifications here

params.nek.problemtype.equation = "incompLinNS"
params.nek.problemtype._set_attrib("solveBaseFlow", "no")
params.oper.elem.staggered = "auto"
# params.NEW_DIR_RESULTS = True

sim = Simul(params)

sim.make.exec("run_fg", resources={"nproc": 4})
```


The first problem is that if we don't put `params.NEW_DIR_RESULTS = True` it doesn't change the `SIZE` file to have `lx2=lx1-2`. If I change manually the `SIZE` file, it gives me the following error just in the first time step

```fortran
Initialization successfully completed   0.19179E-01 sec

Starting time loop ...

     DT/DTCFL/DTFS/DTINIT   0.533E-01   0.533E-01   0.000E+00   0.000E+00
Step      1, t= 5.3344511E-02, DT= 5.3344511E-02, C=  2.000 0.0000E+00 0.0000E+00

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
```
If I put `params.NEW_DIR_RESULTS = True`, I noticed two problems. First, we will have the suffix of the session directory not from `0`. The second, it does not copy the restart file in the new directory (`session`).

**Comment by ashwinvis** [comment]
Note that the `load_for_restart` option can only handle changes in the `.par` file. It would not regenerate or compile the simulation. I am not 100% sure if the restart files would even work the SIZE file changes.

**Comment by paugier** [comment]
@akhoubani I guess you should open a new issue for this particular problem. This issue is closed and it's better to have issues with solvable problems.

I think what you try to do (launching a new completely new simulation from a result file of an old simulation) is something that should be supported. I'm not sure that you should use `load_for_restart` for this case, but at the same time what you wrote seems reasonable (with `params.NEW_DIR_RESULTS = True`).

Remark: I don't think you should need to use `params.nek.problemtype._set_attrib("solveBaseFlow", "no")` in a script. The `_set_attrib` calls should be in the packages and not in the scripts. So I guess something has to be added in `snek5000` or `snek5000-cbox` to add this parameter.

**Comment by paugier** [comment]
Yes, this should be the right way to do. Actually, you don't even need to load the first simulation. You should be able to do

```
from snek5000 import load_params
params = load_params("examples_cbox/simple/cbox_Ra1.835e+08_80x80_8x8_V1.x1._2022-01-04_10-54-25")
```

However, I think `load_params` is a bit hidden in the module `snek5000.params`. I guess an alias should be added in `snek5000`. What do you think @ashwinvis ?

**Comment by akhoubani** [comment]
```python
params = load_params("examples_cbox/simple/cbox_Ra1.835e+08_80x80_8x8_V1.x1._2022-01-04_10-54-25")
[01/05/22 15:37:41] WARNING  The examples_cbox/simple/cbox_Ra1.835e+08_80x80_8x8_V1.x1._2022-01-04_10-54-25/info_solver.xml file is missing! Attempting to guess solver  __init__.py:98
                             from the directory name.                                                                                                                                  
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-1bc6f64ee6c4> in <module>
----> 1 params = load_params("examples_cbox/simple/cbox_Ra1.835e+08_80x80_8x8_V1.x1._2022-01-04_10-54-25")

~/Dev/snek5000/src/snek5000/params.py in load_params(path_dir)
     87     Simul = import_cls_simul(short_name)
     88 
---> 89     return Simul.load_params_from_file(
     90         path_xml=path_dir / "params_simul.xml", path_par=path_dir / f"{short_name}.par"
     91     )

~/Dev/snek5000/src/snek5000/solvers/base.py in load_params_from_file(cls, path_xml, path_par)
     67         if path_xml:
     68             params = Parameters(tag="params")
---> 69             _complete_params_from_xml_file(params, path_xml)
     70         else:
     71             logger.warn(

~/Dev/snek5000/src/snek5000/params.py in _complete_params_from_xml_file(params, path_xml)
    510     _check_path_like(path_xml)
    511 
--> 512     params._load_from_xml_file(str(path_xml))
    513     nek = _get_params_nek(params)
    514     path_recorded_user_params = Path(path_xml).parent / filename_map_user_params

~/mambaforge/envs/env-snek/lib/python3.9/site-packages/fluiddyn/util/paramcontainer.py in _load_from_xml_file(self, path_file)
    500 
    501     def _load_from_xml_file(self, path_file):
--> 502         tree = etree.parse(path_file)
    503         elemxml = tree.getroot()
    504         self._load_from_elemxml(elemxml)

~/mambaforge/envs/env-snek/lib/python3.9/xml/etree/ElementTree.py in parse(source, parser)
   1227     """
   1228     tree = ElementTree()
-> 1229     tree.parse(source, parser)
   1230     return tree
   1231 

~/mambaforge/envs/env-snek/lib/python3.9/xml/etree/ElementTree.py in parse(self, source, parser)
    567         close_source = False
    568         if not hasattr(source, "read"):
--> 569             source = open(source, "rb")
    570             close_source = True
    571         try:

FileNotFoundError: [Errno 2] No such file or directory: 'examples_cbox/simple/cbox_Ra1.835e+08_80x80_8x8_V1.x1._2022-01-04_10-54-25/params_simul.xml'
```

**Comment by ashwinvis** [comment]
It has indeed been a long thread with several mini issues.
